fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = std::path::Path::new(&crate_dir).join("include");
    std::fs::create_dir_all(&out_dir).unwrap();

    let config = cbindgen::Config {
        header: Some(
            "/* tpt-streamforge C API — generated by cbindgen (build.rs). Do not edit. */"
                .to_string(),
        ),
        language: cbindgen::Language::C,
        // `*mut c_void` handles map to `void *` automatically.
        ..Default::default()
    };

    let generated = cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .generate()
        .expect("cbindgen failed to generate the C header");

    // `write_to_file` returns `false` when the header is unchanged, which is
    // a success, not an error.
    let _ = generated.write_to_file(out_dir.join("tpt_streamforge.h"));

    println!("cargo:rerun-if-changed=src/lib.rs");
}
