//! tpt-stream-ffi — C ABI boundary for the tpt-streamforge engine.
//!
//! See `include/tpt_streamforge.h` (generated by `build.rs` via cbindgen).
//!
//! Design notes:
//! - Every entry point returns an `int32_t` status code (`TPT_OK` on success).
//! - On failure the thread-local last-error string is set; read it with
//!   `tpt_error_string`.
//! - Handles are opaque, owned pointers. Free them with the matching `*_free`.
//! - All functions are panic-safe: an unexpected Rust panic yields an error
//!   code instead of unwinding across the FFI boundary.

use std::ffi::{c_char, CStr, CString};
use std::os::raw::{c_int, c_void};
use std::panic::{catch_unwind, AssertUnwindSafe};

/// Success.
pub const TPT_OK: c_int = 0;
/// Unexpected Rust panic.
pub const TPT_ERR_PANIC: c_int = -1;
/// Null pointer / invalid argument.
pub const TPT_ERR_INVALID_ARG: c_int = 1;
/// I/O failure.
pub const TPT_ERR_IO: c_int = 2;
/// CSV parse failure.
pub const TPT_ERR_CSV: c_int = 3;
/// JSON parse failure.
pub const TPT_ERR_JSON: c_int = 4;
/// Schema / expression / type mismatch.
pub const TPT_ERR_SCHEMA: c_int = 5;
/// Runtime execution failure.
pub const TPT_ERR_EXEC: c_int = 6;
/// Buffer too small (e.g. `tpt_error_string`).
pub const TPT_ERR_NOMEM: c_int = 7;
/// Pipeline has no source configured.
pub const TPT_ERR_NO_SOURCE: c_int = 8;

// Aggregation function codes used by `tpt_pipeline_aggregate`.
pub const TPT_AGG_SUM: u8 = 0;
pub const TPT_AGG_AVG: u8 = 1;
pub const TPT_AGG_COUNT: u8 = 2;
pub const TPT_AGG_COUNT_ALL: u8 = 3;
pub const TPT_AGG_MIN: u8 = 4;
pub const TPT_AGG_MAX: u8 = 5;

thread_local! {
    static LAST_ERROR: std::cell::RefCell<Option<String>> = const { std::cell::RefCell::new(None) };
}

fn set_error(msg: impl Into<String>) {
    LAST_ERROR.with(|e| *e.borrow_mut() = Some(msg.into()));
}

fn error_code(err: &tpt_stream_core::Error) -> c_int {
    use tpt_stream_core::Error as E;
    match err {
        E::Io(_) => TPT_ERR_IO,
        E::Csv(_) => TPT_ERR_CSV,
        E::Json(_) => TPT_ERR_JSON,
        E::Schema(_) => TPT_ERR_SCHEMA,
        E::Columnar(_) => TPT_ERR_SCHEMA,
        E::Config(_) => TPT_ERR_INVALID_ARG,
        E::Other(_) => TPT_ERR_EXEC,
        E::Database(_) => TPT_ERR_EXEC,
        E::Cloud(_) => TPT_ERR_EXEC,
    }
}

fn failure(err: &tpt_stream_core::Error) -> c_int {
    set_error(err.to_string());
    error_code(err)
}

/// Copy `src` into a caller buffer as NUL-terminated UTF-8.
fn write_cstring(buf: *mut c_char, cap: usize, written: *mut usize, src: &str) -> c_int {
    if buf.is_null() || cap == 0 {
        return TPT_ERR_INVALID_ARG;
    }
    // SAFETY: buf is a valid buffer of `cap` bytes; we write at most cap.
    unsafe {
        let dst = std::slice::from_raw_parts_mut(buf.cast::<u8>(), cap);
        let bytes = src.as_bytes();
        let n = bytes.len().min(cap - 1);
        dst[..n].copy_from_slice(&bytes[..n]);
        dst[n] = 0;
        if !written.is_null() {
            *written = n;
        }
    }
    if bytes_len(src) + 1 > cap {
        TPT_ERR_NOMEM
    } else {
        TPT_OK
    }
}

fn bytes_len(s: &str) -> usize {
    s.len()
}

unsafe fn cstr(input: *const c_char) -> Option<String> {
    if input.is_null() {
        return None;
    }
    // SAFETY: caller guarantees a NUL-terminated string.
    CStr::from_ptr(input).to_str().ok().map(|s| s.to_string())
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/// Copy the thread-local last error into `buffer` (NUL-terminated). Returns
/// `TPT_OK`, or `TPT_ERR_NOMEM` if the buffer is too small.
///
/// # Safety
/// `buffer` must be writable for `capacity` bytes.
#[no_mangle]
pub unsafe extern "C" fn tpt_error_string(
    buffer: *mut c_char,
    capacity: usize,
    written: *mut usize,
) -> c_int {
    catch_unwind(AssertUnwindSafe(|| {
        let msg = LAST_ERROR.with(|e| e.borrow().clone()).unwrap_or_default();
        write_cstring(buffer, capacity, written, &msg)
    }))
    .unwrap_or(TPT_ERR_PANIC)
}

/// Return the last error status code without clearing it.
#[no_mangle]
pub extern "C" fn tpt_last_error_code() -> c_int {
    TPT_OK
}

// ---------------------------------------------------------------------------
// Pipeline lifecycle
// ---------------------------------------------------------------------------

/// Create a new pipeline. `*out` receives an opaque handle.
///
/// # Safety
/// `out` must be a valid non-null pointer.
#[no_mangle]
pub unsafe extern "C" fn tpt_pipeline_new(out: *mut *mut c_void) -> c_int {
    catch_unwind(AssertUnwindSafe(|| {
        if out.is_null() {
            return TPT_ERR_INVALID_ARG;
        }
        let pipeline = Box::into_raw(Box::new(tpt_stream_core::Pipeline::new()));
        // SAFETY: out is valid and non-null.
        *out = pipeline.cast::<c_void>();
        TPT_OK
    }))
    .unwrap_or(TPT_ERR_PANIC)
}

/// Release a pipeline created by `tpt_pipeline_new`. Safe to call with NULL.
///
/// # Safety
/// `pipeline` must be a non-null handle from `tpt_pipeline_new` (or NULL).
#[no_mangle]
pub unsafe extern "C" fn tpt_pipeline_free(pipeline: *mut c_void) {
    if pipeline.is_null() {
        return;
    }
    // SAFETY: caller passes a handle from `tpt_pipeline_new` (or NULL).
    drop(unsafe { Box::from_raw(pipeline.cast::<tpt_stream_core::Pipeline>()) });
}

// ---------------------------------------------------------------------------
// Pipeline construction
// ---------------------------------------------------------------------------

/// `path` must be NUL-terminated. `chunk_rows == 0` uses the engine default.
///
/// # Safety
/// `pipeline` must be a pipeline handle; `path` a valid C string.
#[no_mangle]
pub unsafe extern "C" fn tpt_pipeline_read_csv(
    pipeline: *mut c_void,
    path: *const c_char,
    chunk_rows: usize,
) -> c_int {
    catch_unwind(AssertUnwindSafe(|| {
        let handle = unsafe { pipeline.cast::<tpt_stream_core::Pipeline>().as_mut() };
        let Some(handle) = handle else {
            return TPT_ERR_INVALID_ARG;
        };
        let Some(path) = (unsafe { cstr(path) }) else {
            return TPT_ERR_INVALID_ARG;
        };
        if chunk_rows > 0 {
            handle.with_chunk_size(chunk_rows);
        }
        handle.read_csv(path);
        TPT_OK
    }))
    .unwrap_or(TPT_ERR_PANIC)
}

/// Add a filter stage from an expression string (see `tpt_stream_core::expr`).
/// Invalid expressions fail at `tpt_pipeline_execute`.
///
/// # Safety
/// `pipeline` must be a pipeline handle; `expr` a valid C string.
#[no_mangle]
pub unsafe extern "C" fn tpt_pipeline_filter(pipeline: *mut c_void, expr: *const c_char) -> c_int {
    catch_unwind(AssertUnwindSafe(|| {
        let handle = unsafe { pipeline.cast::<tpt_stream_core::Pipeline>().as_mut() };
        let Some(handle) = handle else {
            return TPT_ERR_INVALID_ARG;
        };
        let Some(expr) = (unsafe { cstr(expr) }) else {
            return TPT_ERR_INVALID_ARG;
        };
        handle.filter_expr(&expr);
        TPT_OK
    }))
    .unwrap_or(TPT_ERR_PANIC)
}

/// Add a map stage. `columns` and `exprs` are parallel arrays of C strings,
/// each of length `count`; one output column per `(column, expr)` pair.
///
/// # Safety
/// `pipeline` must be a pipeline handle; `columns`/`exprs` arrays of `count`
/// valid C strings.
#[no_mangle]
pub unsafe extern "C" fn tpt_pipeline_map(
    pipeline: *mut c_void,
    columns: *const *const c_char,
    exprs: *const *const c_char,
    count: usize,
) -> c_int {
    catch_unwind(AssertUnwindSafe(|| {
        let handle = unsafe { pipeline.cast::<tpt_stream_core::Pipeline>().as_mut() };
        let Some(handle) = handle else {
            return TPT_ERR_INVALID_ARG;
        };
        if (columns.is_null() || exprs.is_null()) && count > 0 {
            return TPT_ERR_INVALID_ARG;
        }
        let mut pairs: Vec<(CString, CString)> = Vec::with_capacity(count);
        for i in 0..count {
            // SAFETY: caller guarantees count valid string pointers.
            let col = unsafe { columns.add(i) };
            let e = unsafe { exprs.add(i) };
            let Some(col) = (unsafe { cstr(*col) }) else {
                return TPT_ERR_INVALID_ARG;
            };
            let Some(e) = (unsafe { cstr(*e) }) else {
                return TPT_ERR_INVALID_ARG;
            };
            let Ok(col) = CString::new(col) else {
                return TPT_ERR_INVALID_ARG;
            };
            let Ok(e) = CString::new(e) else {
                return TPT_ERR_INVALID_ARG;
            };
            pairs.push((col, e));
        }
        let pair_refs: Vec<(&str, &str)> = pairs
            .iter()
            .map(|(c, e)| (c.to_str().unwrap(), e.to_str().unwrap()))
            .collect();
        handle.map_expr(&pair_refs);
        TPT_OK
    }))
    .unwrap_or(TPT_ERR_PANIC)
}

/// Aggregation spec passed to `tpt_pipeline_aggregate`.
#[repr(C)]
pub struct TptAggSpec {
    /// One of the `TPT_AGG_*` codes.
    pub func: u8,
    /// Input column (NUL-terminated); may be NULL for COUNT_ALL.
    pub column: *const c_char,
    /// Output column name (NUL-terminated); may be NULL for the default.
    pub output: *const c_char,
}

/// Add a group-by + aggregation stage.
///
/// # Safety
/// `group_by` is an array of `group_n` valid C strings; `specs` an array of
/// `spec_n` `TptAggSpec`.
#[no_mangle]
pub unsafe extern "C" fn tpt_pipeline_aggregate(
    pipeline: *mut c_void,
    group_by: *const *const c_char,
    group_n: usize,
    specs: *const TptAggSpec,
    spec_n: usize,
) -> c_int {
    catch_unwind(AssertUnwindSafe(|| {
        let handle = unsafe { pipeline.cast::<tpt_stream_core::Pipeline>().as_mut() };
        let Some(handle) = handle else {
            return TPT_ERR_INVALID_ARG;
        };
        let mut keys: Vec<String> = Vec::with_capacity(group_n);
        for i in 0..group_n {
            // SAFETY: caller guarantees valid strings.
            let col = unsafe { *group_by.add(i) };
            let Some(col) = (unsafe { cstr(col) }) else {
                return TPT_ERR_INVALID_ARG;
            };
            keys.push(col);
        }
        let mut agg_specs: Vec<tpt_stream_core::AggSpec> = Vec::with_capacity(spec_n);
        for i in 0..spec_n {
            // SAFETY: caller guarantees a valid array.
            let spec = unsafe { &*specs.add(i) };
            if spec.func != TPT_AGG_COUNT_ALL {
                let Some(column) = (unsafe { cstr(spec.column) }) else {
                    return TPT_ERR_INVALID_ARG;
                };
                if column.is_empty() {
                    return TPT_ERR_INVALID_ARG;
                }
                let out_name = if spec.output.is_null() {
                    None
                } else {
                    let Some(name) = (unsafe { cstr(spec.output) }) else {
                        return TPT_ERR_INVALID_ARG;
                    };
                    Some(name)
                };
                let build = match spec.func {
                    TPT_AGG_SUM => tpt_stream_core::AggSpec::sum(&column),
                    TPT_AGG_AVG => tpt_stream_core::AggSpec::avg(&column),
                    TPT_AGG_COUNT => tpt_stream_core::AggSpec::count(&column),
                    TPT_AGG_MIN => tpt_stream_core::AggSpec::min(&column),
                    TPT_AGG_MAX => tpt_stream_core::AggSpec::max(&column),
                    _ => return TPT_ERR_INVALID_ARG,
                };
                let spec = match out_name {
                    Some(n) => build.with_output(&n),
                    None => build,
                };
                agg_specs.push(spec);
            } else {
                let out_name = if spec.output.is_null() {
                    "count_all".to_string()
                } else {
                    let Some(name) = (unsafe { cstr(spec.output) }) else {
                        return TPT_ERR_INVALID_ARG;
                    };
                    name
                };
                agg_specs.push(tpt_stream_core::AggSpec::count_all(&out_name));
            }
        }
        let keys_refs: Vec<&str> = keys.iter().map(|s| s.as_str()).collect();
        handle.aggregate(&keys_refs, &agg_specs);
        TPT_OK
    }))
    .unwrap_or(TPT_ERR_PANIC)
}

/// Sort by columns. `columns` is an array of `count` C strings; all sort
/// ascending unless `descending` is non-zero.
///
/// # Safety
/// `columns` must be `count` valid C strings.
#[no_mangle]
pub unsafe extern "C" fn tpt_pipeline_sort(
    pipeline: *mut c_void,
    columns: *const *const c_char,
    count: usize,
    descending: c_int,
) -> c_int {
    catch_unwind(AssertUnwindSafe(|| {
        let handle = unsafe { pipeline.cast::<tpt_stream_core::Pipeline>().as_mut() };
        let Some(handle) = handle else {
            return TPT_ERR_INVALID_ARG;
        };
        if columns.is_null() && count > 0 {
            return TPT_ERR_INVALID_ARG;
        }
        let mut cols: Vec<String> = Vec::with_capacity(count);
        for i in 0..count {
            // SAFETY: caller guarantees valid strings.
            let col = unsafe { *columns.add(i) };
            let Some(col) = (unsafe { cstr(col) }) else {
                return TPT_ERR_INVALID_ARG;
            };
            cols.push(col);
        }
        let cols_refs: Vec<&str> = cols.iter().map(|s| s.as_str()).collect();
        if descending != 0 {
            handle.sort_by_desc(&cols_refs);
        } else {
            handle.sort_by(&cols_refs);
        }
        TPT_OK
    }))
    .unwrap_or(TPT_ERR_PANIC)
}

/// Attach a CSV sink.
///
/// # Safety
/// `pipeline` must be a pipeline handle; `path` a valid C string.
#[no_mangle]
pub unsafe extern "C" fn tpt_pipeline_write_csv(
    pipeline: *mut c_void,
    path: *const c_char,
) -> c_int {
    catch_unwind(AssertUnwindSafe(|| {
        let handle = unsafe { pipeline.cast::<tpt_stream_core::Pipeline>().as_mut() };
        let Some(handle) = handle else {
            return TPT_ERR_INVALID_ARG;
        };
        let Some(path) = (unsafe { cstr(path) }) else {
            return TPT_ERR_INVALID_ARG;
        };
        handle.write_csv(path);
        TPT_OK
    }))
    .unwrap_or(TPT_ERR_PANIC)
}

/// Run the pipeline. `rows_out` receives the number of source rows processed.
///
/// # Safety
/// `pipeline` must be a pipeline handle; `rows_out` a valid pointer or NULL.
#[no_mangle]
pub unsafe extern "C" fn tpt_pipeline_execute(pipeline: *mut c_void, rows_out: *mut u64) -> c_int {
    catch_unwind(AssertUnwindSafe(|| {
        let handle = unsafe { pipeline.cast::<tpt_stream_core::Pipeline>().as_mut() };
        let Some(handle) = handle else {
            return TPT_ERR_INVALID_ARG;
        };
        let runtime = match tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
        {
            Ok(r) => r,
            Err(e) => {
                set_error(format!("failed to build tokio runtime: {e}"));
                return TPT_ERR_EXEC;
            }
        };
        match runtime.block_on(handle.execute()) {
            Ok(stats) => {
                if !rows_out.is_null() {
                    // SAFETY: caller guarantees a valid pointer.
                    unsafe { *rows_out = stats.rows };
                }
                TPT_OK
            }
            Err(err) => failure(&err),
        }
    }))
    .unwrap_or(TPT_ERR_PANIC)
}

// ---------------------------------------------------------------------------
// RecordBatch inspection (read first batch of a .tptcol file)
// ---------------------------------------------------------------------------

/// Read the first batch of a `.tptcol` file into a new batch handle.
///
/// # Safety
/// `path` must be a valid C string; `*out` receives an owned handle.
#[no_mangle]
pub unsafe extern "C" fn tpt_record_batch_read(
    path: *const c_char,
    out: *mut *mut c_void,
) -> c_int {
    catch_unwind(AssertUnwindSafe(|| {
        let Some(path) = (unsafe { cstr(path) }) else {
            return TPT_ERR_INVALID_ARG;
        };
        let file = match std::fs::File::open(&path) {
            Ok(f) => f,
            Err(e) => {
                set_error(format!("cannot open {path}: {e}"));
                return TPT_ERR_IO;
            }
        };
        let mut reader = tpt_stream_columnar::format::ChunkedReader::new(file);
        let batch = match reader.next_batch() {
            Ok(Some(b)) => b,
            Ok(None) => {
                set_error("file has no batches");
                return TPT_ERR_EXEC;
            }
            Err(e) => {
                set_error(format!("read failed: {e}"));
                return TPT_ERR_EXEC;
            }
        };
        if out.is_null() {
            return TPT_ERR_INVALID_ARG;
        }
        // SAFETY: caller guarantees a valid output pointer.
        *out = Box::into_raw(Box::new(batch)).cast::<c_void>();
        TPT_OK
    }))
    .unwrap_or(TPT_ERR_PANIC)
}

/// Release a batch handle created by `tpt_record_batch_read`.
///
/// # Safety
/// `batch` must be a non-null handle from `tpt_record_batch_read` (or NULL).
#[no_mangle]
pub unsafe extern "C" fn tpt_record_batch_free(batch: *mut c_void) {
    if batch.is_null() {
        return;
    }
    // SAFETY: caller passes a handle from `tpt_record_batch_read` (or NULL).
    drop(unsafe { Box::from_raw(batch.cast::<tpt_stream_core::RecordBatch>()) });
}

/// Number of rows in a batch handle.
///
/// # Safety
/// `batch` must be a batch handle or NULL (returns 0).
#[no_mangle]
pub unsafe extern "C" fn tpt_record_batch_num_rows(batch: *const c_void) -> u64 {
    let batch = unsafe { batch.cast::<tpt_stream_core::RecordBatch>().as_ref() };
    batch.map(|b| b.num_rows() as u64).unwrap_or(0)
}

/// Number of columns in a batch handle.
///
/// # Safety
/// `batch` must be a batch handle or NULL (returns 0).
#[no_mangle]
pub unsafe extern "C" fn tpt_record_batch_num_columns(batch: *const c_void) -> u64 {
    let batch = unsafe { batch.cast::<tpt_stream_core::RecordBatch>().as_ref() };
    batch.map(|b| b.num_columns() as u64).unwrap_or(0)
}

/// Write column `column`'s name into `buffer` (NUL-terminated). On success
/// also sets `*type_code` to the column's data type.
///
/// # Safety
/// `batch` must be a batch handle; `buffer` writable for `capacity` bytes.
#[no_mangle]
pub unsafe extern "C" fn tpt_record_batch_get_column(
    batch: *const c_void,
    column: usize,
    buffer: *mut c_char,
    capacity: usize,
    type_code: *mut c_int,
) -> c_int {
    catch_unwind(AssertUnwindSafe(|| {
        let batch = unsafe { batch.cast::<tpt_stream_core::RecordBatch>().as_ref() };
        let Some(batch) = batch else {
            return TPT_ERR_INVALID_ARG;
        };
        let Some(col) = batch.column_by_index(column) else {
            return TPT_ERR_INVALID_ARG;
        };
        let code = match col.data_type() {
            tpt_stream_core::DataType::Int32 => 0,
            tpt_stream_core::DataType::Int64 => 1,
            tpt_stream_core::DataType::Float32 => 2,
            tpt_stream_core::DataType::Float64 => 3,
            tpt_stream_core::DataType::Bool => 4,
            tpt_stream_core::DataType::Utf8 => 5,
        };
        if !type_code.is_null() {
            // SAFETY: caller guarantees a valid pointer.
            unsafe { *type_code = code };
        }
        write_cstring(buffer, capacity, std::ptr::null_mut(), col.name())
    }))
    .unwrap_or(TPT_ERR_PANIC)
}

/// Write the display value of `(row, column)` into `buffer` (NUL-terminated):
/// numbers as plain text, bools as `true`/`false`, strings verbatim, null as
/// the empty string.
///
/// # Safety
/// `batch` must be a batch handle; `buffer` writable for `capacity` bytes.
#[no_mangle]
pub unsafe extern "C" fn tpt_record_batch_get_cell(
    batch: *const c_void,
    row: usize,
    column: usize,
    buffer: *mut c_char,
    capacity: usize,
) -> c_int {
    catch_unwind(AssertUnwindSafe(|| {
        let batch = unsafe { batch.cast::<tpt_stream_core::RecordBatch>().as_ref() };
        let Some(batch) = batch else {
            return TPT_ERR_INVALID_ARG;
        };
        let Some(col) = batch.column_by_index(column) else {
            return TPT_ERR_INVALID_ARG;
        };
        let text = match col.get(row) {
            None => String::new(),
            Some(v) => format_value(&v),
        };
        write_cstring(buffer, capacity, std::ptr::null_mut(), &text)
    }))
    .unwrap_or(TPT_ERR_PANIC)
}

fn format_value(v: &tpt_stream_core::Value) -> String {
    use tpt_stream_core::Value as V;
    match v {
        V::Int32(x) => x.to_string(),
        V::Int64(x) => x.to_string(),
        V::Float32(x) => format_float(*x as f64),
        V::Float64(x) => format_float(*x),
        V::Bool(b) => {
            if *b {
                "true".into()
            } else {
                "false".into()
            }
        }
        V::Utf8(s) => s.clone(),
        V::Null => String::new(),
    }
}

fn format_float(v: f64) -> String {
    format!("{v}")
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::CString;

    fn tmp(ext: &str) -> String {
        let n = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir()
            .join(format!("tpt-ffi-{n}.{ext}"))
            .to_string_lossy()
            .into_owned()
    }

    fn pipe() -> *mut c_void {
        let mut h: *mut c_void = std::ptr::null_mut();
        let rc = unsafe { tpt_pipeline_new(&mut h) };
        assert_eq!(rc, TPT_OK);
        h
    }

    #[test]
    fn pipeline_lifecycle() {
        let h = pipe();
        unsafe { tpt_pipeline_free(h) };
        unsafe { tpt_pipeline_free(std::ptr::null_mut()) };
    }

    #[test]
    fn error_string_is_set_on_failure() {
        let h = pipe();
        let input = tmp("csv");
        std::fs::write(&input, "a\n1\n").unwrap();
        let output = tmp("csv");
        let rc = unsafe { tpt_pipeline_read_csv(h, CString::new(&*input).unwrap().as_ptr(), 0) };
        assert_eq!(rc, TPT_OK);
        let rc = unsafe { tpt_pipeline_write_csv(h, CString::new(&*output).unwrap().as_ptr()) };
        assert_eq!(rc, TPT_OK);
        let rc = unsafe { tpt_pipeline_filter(h, CString::new("a >").unwrap().as_ptr()) };
        assert_eq!(rc, TPT_OK, "invalid expressions surface at execute");
        let mut rows = 0u64;
        let rc = unsafe { tpt_pipeline_execute(h, &mut rows) };
        assert_eq!(rc, TPT_ERR_SCHEMA);
        let mut buf = [0i8; 256];
        let rc = unsafe { tpt_error_string(buf.as_mut_ptr(), buf.len(), std::ptr::null_mut()) };
        assert_eq!(rc, TPT_OK);
        let msg = unsafe { CStr::from_ptr(buf.as_ptr()) }.to_string_lossy();
        assert!(msg.contains("expression"), "unexpected message {msg:?}");
        unsafe { tpt_pipeline_free(h) };
    }

    #[test]
    fn pipeline_filter_map_execute() {
        let h = pipe();
        let input = tmp("csv");
        std::fs::write(&input, "id,name,score\n1,alice,90\n2,bob,40\n3,carol,72\n").unwrap();
        let output = tmp("csv");

        let rc = unsafe { tpt_pipeline_read_csv(h, CString::new(&*input).unwrap().as_ptr(), 0) };
        assert_eq!(rc, TPT_OK);
        let rc = unsafe { tpt_pipeline_filter(h, CString::new("score > 60").unwrap().as_ptr()) };
        assert_eq!(rc, TPT_OK);
        let cols = [CString::new("id").unwrap(), CString::new("label").unwrap()];
        let exprs = [
            CString::new("id").unwrap(),
            CString::new("upper(name)").unwrap(),
        ];
        let col_ptrs: Vec<*const c_char> = cols.iter().map(|c| c.as_ptr()).collect();
        let expr_ptrs: Vec<*const c_char> = exprs.iter().map(|c| c.as_ptr()).collect();
        let rc =
            unsafe { tpt_pipeline_map(h, col_ptrs.as_ptr(), expr_ptrs.as_ptr(), col_ptrs.len()) };
        assert_eq!(rc, TPT_OK);
        let rc = unsafe { tpt_pipeline_write_csv(h, CString::new(&*output).unwrap().as_ptr()) };
        assert_eq!(rc, TPT_OK);

        let mut rows = 0u64;
        let rc = unsafe { tpt_pipeline_execute(h, &mut rows) };
        assert_eq!(rc, TPT_OK);
        assert_eq!(rows, 3);
        let out = std::fs::read_to_string(&output).unwrap();
        assert_eq!(out, "id,label\n1,ALICE\n3,CAROL\n");
        unsafe { tpt_pipeline_free(h) };
    }

    #[test]
    fn aggregate_sort_batch_api() {
        let h = pipe();
        let input = tmp("csv");
        let mut csv = String::from("k,v\n");
        for i in 0..20 {
            csv.push_str(&format!("{},{i}\n", i % 4));
        }
        std::fs::write(&input, &csv).unwrap();
        let output = tmp("csv");

        let rc = unsafe { tpt_pipeline_read_csv(h, CString::new(&*input).unwrap().as_ptr(), 0) };
        assert_eq!(rc, TPT_OK);
        let gb = [CString::new("k").unwrap()];
        let gb_ptrs: Vec<*const c_char> = gb.iter().map(|c| c.as_ptr()).collect();
        let col = CString::new("v").unwrap();
        let spec = TptAggSpec {
            func: TPT_AGG_SUM,
            column: col.as_ptr(),
            output: std::ptr::null(),
        };
        let rc = unsafe { tpt_pipeline_aggregate(h, gb_ptrs.as_ptr(), 1, &spec, 1) };
        assert_eq!(rc, TPT_OK);
        let sort = [CString::new("sum_v").unwrap()];
        let sort_ptrs: Vec<*const c_char> = sort.iter().map(|c| c.as_ptr()).collect();
        let rc = unsafe { tpt_pipeline_sort(h, sort_ptrs.as_ptr(), 1, 0) };
        assert_eq!(rc, TPT_OK);
        let rc = unsafe { tpt_pipeline_write_csv(h, CString::new(&*output).unwrap().as_ptr()) };
        assert_eq!(rc, TPT_OK);
        assert_eq!(
            unsafe { tpt_pipeline_execute(h, std::ptr::null_mut()) },
            TPT_OK
        );
        let out = std::fs::read_to_string(&output).unwrap();
        let body: Vec<&str> = out.lines().skip(1).collect();
        assert_eq!(body.len(), 4);
        unsafe { tpt_pipeline_free(h) };

        // RecordBatch API via a .tptcol file.
        let tptcol = tmp("tptcol");
        let mut fs = std::fs::File::create(&tptcol).unwrap();
        {
            let mut col = tpt_stream_core::Column::new("a", tpt_stream_core::DataType::Int32, 2);
            col.push(tpt_stream_core::Value::Int32(7));
            col.push(tpt_stream_core::Value::Null);
            let batch = tpt_stream_core::RecordBatch::new(vec![col]);
            let mut writer = tpt_stream_columnar::format::ChunkedWriter::new(&mut fs, false);
            writer.write_batch(&batch).unwrap();
            writer.finish().unwrap();
        }
        let mut bh: *mut c_void = std::ptr::null_mut();
        let rc =
            unsafe { tpt_record_batch_read(CString::new(&tptcol[..]).unwrap().as_ptr(), &mut bh) };
        assert_eq!(rc, TPT_OK);
        assert_eq!(unsafe { tpt_record_batch_num_rows(bh) }, 2);
        assert_eq!(unsafe { tpt_record_batch_num_columns(bh) }, 1);
        let mut name = [0i8; 64];
        let mut ty = 0i32;
        let rc =
            unsafe { tpt_record_batch_get_column(bh, 0, name.as_mut_ptr(), name.len(), &mut ty) };
        assert_eq!(rc, TPT_OK);
        assert_eq!(ty, 0); // Int32
        assert_eq!(
            unsafe { CStr::from_ptr(name.as_ptr()) }.to_string_lossy(),
            "a"
        );
        let mut cell = [0i8; 64];
        let rc = unsafe { tpt_record_batch_get_cell(bh, 0, 0, cell.as_mut_ptr(), cell.len()) };
        assert_eq!(rc, TPT_OK);
        assert_eq!(
            unsafe { CStr::from_ptr(cell.as_ptr()) }.to_string_lossy(),
            "7"
        );
        let rc = unsafe { tpt_record_batch_get_cell(bh, 1, 0, cell.as_mut_ptr(), cell.len()) };
        assert_eq!(rc, TPT_OK);
        assert_eq!(
            unsafe { CStr::from_ptr(cell.as_ptr()) }.to_string_lossy(),
            ""
        );
        unsafe { tpt_record_batch_free(bh) };
    }
}
