/* tpt-streamforge C API — generated by cbindgen (build.rs). Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success.
 */
#define TPT_OK 0

/**
 * Unexpected Rust panic.
 */
#define TPT_ERR_PANIC -1

/**
 * Null pointer / invalid argument.
 */
#define TPT_ERR_INVALID_ARG 1

/**
 * I/O failure.
 */
#define TPT_ERR_IO 2

/**
 * CSV parse failure.
 */
#define TPT_ERR_CSV 3

/**
 * JSON parse failure.
 */
#define TPT_ERR_JSON 4

/**
 * Schema / expression / type mismatch.
 */
#define TPT_ERR_SCHEMA 5

/**
 * Runtime execution failure.
 */
#define TPT_ERR_EXEC 6

/**
 * Buffer too small (e.g. `tpt_error_string`).
 */
#define TPT_ERR_NOMEM 7

/**
 * Pipeline has no source configured.
 */
#define TPT_ERR_NO_SOURCE 8

#define TPT_AGG_SUM 0

#define TPT_AGG_AVG 1

#define TPT_AGG_COUNT 2

#define TPT_AGG_COUNT_ALL 3

#define TPT_AGG_MIN 4

#define TPT_AGG_MAX 5

/**
 * Aggregation spec passed to `tpt_pipeline_aggregate`.
 */
typedef struct TptAggSpec {
  /**
   * One of the `TPT_AGG_*` codes.
   */
  uint8_t func;
  /**
   * Input column (NUL-terminated); may be NULL for COUNT_ALL.
   */
  const char *column;
  /**
   * Output column name (NUL-terminated); may be NULL for the default.
   */
  const char *output;
} TptAggSpec;

/**
 * Copy the thread-local last error into `buffer` (NUL-terminated). Returns
 * `TPT_OK`, or `TPT_ERR_NOMEM` if the buffer is too small.
 *
 * # Safety
 * `buffer` must be writable for `capacity` bytes.
 */
int tpt_error_string(char *buffer, uintptr_t capacity, uintptr_t *written);

/**
 * Return the last error status code without clearing it.
 */
int tpt_last_error_code(void);

/**
 * Create a new pipeline. `*out` receives an opaque handle.
 *
 * # Safety
 * `out` must be a valid non-null pointer.
 */
int tpt_pipeline_new(void **out);

/**
 * Release a pipeline created by `tpt_pipeline_new`. Safe to call with NULL.
 *
 * # Safety
 * `pipeline` must be a non-null handle from `tpt_pipeline_new` (or NULL).
 */
void tpt_pipeline_free(void *pipeline);

/**
 * `path` must be NUL-terminated. `chunk_rows == 0` uses the engine default.
 *
 * # Safety
 * `pipeline` must be a pipeline handle; `path` a valid C string.
 */
int tpt_pipeline_read_csv(void *pipeline, const char *path, uintptr_t chunk_rows);

/**
 * Add a filter stage from an expression string (see `tpt_stream_core::expr`).
 * Invalid expressions fail at `tpt_pipeline_execute`.
 *
 * # Safety
 * `pipeline` must be a pipeline handle; `expr` a valid C string.
 */
int tpt_pipeline_filter(void *pipeline, const char *expr);

/**
 * Add a map stage. `columns` and `exprs` are parallel arrays of C strings,
 * each of length `count`; one output column per `(column, expr)` pair.
 *
 * # Safety
 * `pipeline` must be a pipeline handle; `columns`/`exprs` arrays of `count`
 * valid C strings.
 */
int tpt_pipeline_map(void *pipeline,
                     const char *const *columns,
                     const char *const *exprs,
                     uintptr_t count);

/**
 * Add a group-by + aggregation stage.
 *
 * # Safety
 * `group_by` is an array of `group_n` valid C strings; `specs` an array of
 * `spec_n` `TptAggSpec`.
 */
int tpt_pipeline_aggregate(void *pipeline,
                           const char *const *group_by,
                           uintptr_t group_n,
                           const struct TptAggSpec *specs,
                           uintptr_t spec_n);

/**
 * Sort by columns. `columns` is an array of `count` C strings; all sort
 * ascending unless `descending` is non-zero.
 *
 * # Safety
 * `columns` must be `count` valid C strings.
 */
int tpt_pipeline_sort(void *pipeline, const char *const *columns, uintptr_t count, int descending);

/**
 * Attach a CSV sink.
 *
 * # Safety
 * `pipeline` must be a pipeline handle; `path` a valid C string.
 */
int tpt_pipeline_write_csv(void *pipeline, const char *path);

/**
 * Run the pipeline. `rows_out` receives the number of source rows processed.
 *
 * # Safety
 * `pipeline` must be a pipeline handle; `rows_out` a valid pointer or NULL.
 */
int tpt_pipeline_execute(void *pipeline, uint64_t *rows_out);

/**
 * Read the first batch of a `.tptcol` file into a new batch handle.
 *
 * # Safety
 * `path` must be a valid C string; `*out` receives an owned handle.
 */
int tpt_record_batch_read(const char *path, void **out);

/**
 * Release a batch handle created by `tpt_record_batch_read`.
 *
 * # Safety
 * `batch` must be a non-null handle from `tpt_record_batch_read` (or NULL).
 */
void tpt_record_batch_free(void *batch);

/**
 * Number of rows in a batch handle.
 *
 * # Safety
 * `batch` must be a batch handle or NULL (returns 0).
 */
uint64_t tpt_record_batch_num_rows(const void *batch);

/**
 * Number of columns in a batch handle.
 *
 * # Safety
 * `batch` must be a batch handle or NULL (returns 0).
 */
uint64_t tpt_record_batch_num_columns(const void *batch);

/**
 * Write column `column`'s name into `buffer` (NUL-terminated). On success
 * also sets `*type_code` to the column's data type.
 *
 * # Safety
 * `batch` must be a batch handle; `buffer` writable for `capacity` bytes.
 */
int tpt_record_batch_get_column(const void *batch,
                                uintptr_t column,
                                char *buffer,
                                uintptr_t capacity,
                                int *type_code);

/**
 * Write the display value of `(row, column)` into `buffer` (NUL-terminated):
 * numbers as plain text, bools as `true`/`false`, strings verbatim, null as
 * the empty string.
 *
 * # Safety
 * `batch` must be a batch handle; `buffer` writable for `capacity` bytes.
 */
int tpt_record_batch_get_cell(const void *batch,
                              uintptr_t row,
                              uintptr_t column,
                              char *buffer,
                              uintptr_t capacity);
